#include "MainController.h"
#include "../structs/Keys.h"

// #include <csignal>


using namespace std;


namespace controller {


    ReturnMessage MainController::processInput() {
        ofstream log("inputs", ios_base::app);

        int ch = window.getChar();
        log << ch << endl;


        // avoid the echoing of ANSI escape sequence generated by ncurses
        // after we hit an arrow key after a resizing event
        // Filter out unwanted sequences after resizing


        inputBuffer.push_back(ch);


        ReturnMessage returnMessage;

        if (dynamic_cast<mode::InsertMode *>(currentMode)) {
            returnMessage = currentMode->processInput(inputBuffer);
            if (returnMessage == ReturnMessage::NORMAL) {
                currentMode = normal_mode.get();
            }
            inputBuffer.clear();
            return returnMessage;
        }

        // else mode is Normal Mode
        returnMessage = currentMode->processInput(inputBuffer);
        
        if (returnMessage == ReturnMessage::CLEARBUFFER) {
            inputBuffer.clear();
        }
        else if (returnMessage == ReturnMessage::INSERT) {
            currentMode = insert_mode.get();
        }
        
        return returnMessage;        
    }












}

